name: Node.js CI

on:
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: ./javascript-ascent

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "javascript-ascent/package-lock.json"
          node-version: ${{ matrix.node-version }}
      - run: npx prettier . --write
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:ci
